[package]
name = "worldedit"
version = "0.1.0"
authors = ["sagan <camjanssen120@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quill-prototype = "0.0.0-prototype.1"
rand = "0.7.3"
